Hello Microverse Project
kelomo2502/hello-microverse pull request #1
Opened 2022-03-15 13:22 UTC by kelomo2502

I Created a new GitHub repo named Hello-Microverse and a new feature branch was also created for commits and subsequent pull request.
A  .gitignore file was added according to instructions given.
Linters  for HTML and CSS were installed and used to lint the index.html  and style.css  respectively.
A descriptive README.md file was also added.

2022-03-15 13:42 UTC, Whoistolu requested changes
Hi @kelomo2502 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️

- [ ]  _Check the inline comments under the review for sections to improve._

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-15 13:42 UTC, Whoistolu commented on .gitignore
> +node_modules
- [ ] [REQUIRED] Kindly add the `test.md` file also to the `.gitignore` file. You currently have the `test.md` file pushed directly to Github. This will help prevent unnecessary files like `node_modules` and `test.md` files to be pushed to GitHub.

2022-03-15 13:42 UTC, Whoistolu commented on README.md
> +
- [ ] [REQUIRED] Kindly update the "Getting Started" part by listing sets of instructions needed to get this project working on another user's machine locally.

2022-03-15 13:42 UTC, Whoistolu commented on README.md
> +### Deployment
- [ ] [REQUIRED] Please remove this part of the README file as you currently do not have them in use. This will enable you to have a clean and organized README.

2022-03-15 13:42 UTC, Whoistolu commented on README.md
> +- LinkedIn: [LinkedIn](https://linkedin.com/in/linkedinhandle)
- [ ] [REQUIRED] Kindly maintain just one author for now, which is you. Also, edit the links to personalize them so that visitors will be able to contact you if need be. The README is a very important file that gives visitors an idea of what the project is about and details about the developer of the project.

2022-03-16 14:29 UTC, kelomo2502 commented on README.md
> +
Dear Reviewer, I have tried implementing your observations on this project. However I have been having a few challenges which keep messing up my code further so i decided to start another one from scratch. Please I would like to seek your permission to delete this repo and do a new one all together. Thanks for your prompt response.

2022-03-16 15:58 UTC, closed without merging

2022-03-16 23:05 UTC, Whoistolu commented on README.md
> +
Hello @kelomo2502 , I understand how you feel, however, you should not delete this repository nor close this branch. What are the exact issues messing with your code, let me help you out?